"""unique email

Revision ID: 578269213921
Revises: f42c5ac35eb3
Create Date: 2025-12-07 13:35:13.465127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "578269213921"
down_revision: Union[str, None] = "f42c5ac35eb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    constraints = sa.inspect(op.get_bind()).get_unique_constraints("users")
    constraint = next(
        (item for item in constraints if item.get("column_names") == ["email"]), None
    )
    if constraint:
        name = constraint.get("name")
        if isinstance(name, str):
            op.drop_constraint(name, "users", type_="unique")
    # ### end Alembic commands ###
